"""
Virtual Museum AI Curator — FastAPI Web Server (Phase 4 — Fully Audited)

Endpoints:
  GET  /         — Root health check
  GET  /health   — Health probe
  POST /ask      — Main RAG Q&A endpoint (Phase 1-3 pipeline)

Audit fixes applied:
  - artifact_id is now forwarded to the RAG pipeline
  - Pydantic v2 validators updated
  - CORS updated with correct origins
  - Clear error responses without stack trace leakage
"""

import os
import sys
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, field_validator
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware

# Ensure backend root is in module search path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Load .env file before importing rag modules that may need API keys
try:
    from dotenv import load_dotenv
    load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), ".env"))
    print("[STARTUP] Loaded backend .env")
except ImportError:
    print("[STARTUP] Warning: python-dotenv not installed. Using system environment variables.")

from rag.rag_pipeline import answer_question, REFUSAL_MESSAGE
from rag.llm import validate_tone

# Allowed frontend origin (reads from env, falls back to localhost:3000)
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000").rstrip("/")

app = FastAPI(
    title="Virtual Museum AI Curator API",
    description="RAG & XAI Backend for 3D Virtual Museum AR/VR Experience (Phases 1–3)",
    version="4.1.0",
)

# ── CORS ──────────────────────────────────────────────────────────────────────
# Allow local dev servers, configured FRONTEND_URL, and all Vercel deployment origins
_cors_origins = list({
    FRONTEND_URL,
    FRONTEND_URL + "/",
    "https://mueseum-3d.vercel.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://localhost:8080"
})
print(f"[STARTUP] CORS allowed origins: {_cors_origins}")

app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_origin_regex=r"https://.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── PYDANTIC MODELS ───────────────────────────────────────────────────────────

class AskRequest(BaseModel):
    session_id: Optional[str] = Field(
        default=None,
        description="Anonymous visitor session UUID. Auto-generated by backend if absent."
    )
    question: str = Field(
        ...,
        description="Visitor question text (1–1000 characters)."
    )
    artifact_id: Optional[str] = Field(
        default=None,
        description="ID of the currently selected 3D artifact (e.g. 'ART001'). Enables contextual answers."
    )
    tone: str = Field(
        default="educational",
        description="Curator presentation style: 'educational', 'concise', or 'friendly'."
    )

    @field_validator("question")
    @classmethod
    def validate_question_text(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Question text cannot be empty.")
        if len(v.strip()) > 1000:
            raise ValueError("Question is too long (maximum 1000 characters).")
        return v.strip()

    @field_validator("tone")
    @classmethod
    def validate_tone_setting(cls, v: str) -> str:
        return validate_tone(v)

    @field_validator("artifact_id")
    @classmethod
    def validate_artifact_id(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        cleaned = v.strip()
        return cleaned if cleaned else None


class SourcePayload(BaseModel):
    artifact: str
    gallery: str


class SuggestionPayload(BaseModel):
    artifact_id: str
    artifact_name: str
    gallery: str
    similarity: float


class AskResponse(BaseModel):
    answer: str
    source: Optional[SourcePayload] = None
    confidence: float
    evidence: Optional[str] = None
    refused: bool
    session_id: str
    tone: str
    related_suggestions: List[SuggestionPayload] = []


# ── ENDPOINTS ─────────────────────────────────────────────────────────────────

@app.get("/", tags=["Health"])
def root_status():
    """Root health check."""
    return {
        "status": "ok",
        "service": "museum-ai-curator",
        "version": "4.1.0",
    }


@app.get("/health", tags=["Health"])
def health_check():
    """Dedicated health probe."""
    return {"status": "healthy"}


@app.post("/ask", response_model=AskResponse, tags=["AI Curator"])
def ask_curator_endpoint(payload: AskRequest):
    """
    Main AI Curator RAG endpoint.

    Accepts a visitor question and optional selected artifact ID.
    Routes through Phase 1 retrieval → Phase 2 threshold → Phase 3 personalization.
    Returns a grounded, source-attributed response or a structured refusal.
    """
    print(f"\n[API DEBUG] Received artifact_id: {payload.artifact_id}")
    print(f"[API DEBUG] Received question: \"{payload.question}\"")
    print(f"[API DEBUG] Session ID: {payload.session_id or '(new session)'}")
    print(f"[API DEBUG] Tone: {payload.tone}")

    try:
        result = answer_question(
            question=payload.question,
            session_id=payload.session_id,
            tone=payload.tone,
            artifact_id=payload.artifact_id,  # Forwarded to RAG pipeline
        )

        resolved_art = result.get("source", {}).get("artifact") if result.get("source") else "None (Refused/General)"
        print(f"[API DEBUG] Resolved artifact: {resolved_art}")
        print(f"[API DEBUG] Refused: {result.get('refused', False)}")
        print(f"[API DEBUG] Confidence: {result.get('confidence', 0.0):.4f}")
        print(f"[API DEBUG] LLM called: {result.get('llm_called', False)}")

        return result

    except ValueError as ve:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(ve),
        )
    except Exception as err:
        # Log full error server-side but do NOT expose stack trace to frontend
        print(f"[API ERROR] Internal error in /ask endpoint: {type(err).__name__}: {err}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An error occurred while processing your query. Please try again.",
        )
