"""
Grounded LLM Integration Module (Phase 2 XAI Layer)

Connects to Groq API (or Gemini/OpenAI API) to generate
strictly grounded answers using ONLY retrieved artifact metadata.

No outside knowledge or ungrounded facts are permitted.
"""

import os
from typing import Dict, Any

# Load environment variables from .env
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# System prompt forcing strict factual grounding on retrieved artifact
SYSTEM_PROMPT_TEMPLATE = """You are an AI curator for a virtual museum.

Answer the user's question ONLY using the supplied curated artifact information.

Do not use outside knowledge.

Do not invent facts, dates, names, measurements, historical events or interpretations.

If the supplied artifact information does not contain enough information to answer the question, explicitly state that the information is not available in the curated knowledge base.

Keep the answer concise, clear and suitable for a museum visitor.

ARTIFACT INFORMATION:
Name: {name}
Gallery: {gallery}
Category: {category}
Institution: {institution}
Period/Origin: {period} ({origin})
Description: {description}
Historical Significance: {significance}
Material & Dimensions: {material}, {dimensions}

USER QUESTION:
{question}"""


def get_api_credentials():
    """Reads API keys from environment variables."""
    groq_key = os.environ.get("GROQ_API_KEY") or os.environ.get("GROK_API_KEY")
    gemini_key = os.environ.get("GEMINI_API_KEY")
    llm_key = os.environ.get("LLM_API_KEY")
    return {
        "groq": groq_key.strip() if groq_key else None,
        "gemini": gemini_key.strip() if gemini_key else None,
        "generic": llm_key.strip() if llm_key else None
    }


def _call_groq_sdk(prompt: str, api_key: str) -> str:
    """Calls Groq API using the official Groq Python SDK with available model endpoints."""
    from groq import Groq

    client = Groq(api_key=api_key)
    
    candidate_models = [
        "openai/gpt-oss-20b",
        "qwen/qwen3.8-27b",
        "groq/compound-mini",
        "openai/gpt-oss-120b"
    ]

    last_err = None
    for model_name in candidate_models:
        try:
            completion = client.chat.completions.create(
                model=model_name,
                messages=[
                    {"role": "system", "content": "You are a strict, grounded virtual museum curator."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.2,
                max_tokens=512
            )
            return completion.choices[0].message.content.strip()
        except Exception as e:
            last_err = e
            continue

    raise RuntimeError(f"All Groq models failed ({last_err})")


def generate_grounded_answer(question: str, artifact: Dict[str, Any]) -> str:
    """
    Calls configured LLM API (Groq/Gemini) with strict grounding prompt.
    
    :param question: User question string
    :param artifact: Retrieved artifact metadata dictionary
    :return: Grounded answer string generated by LLM
    """
    keys = get_api_credentials()

    # Extract artifact context fields
    name = artifact.get("name", "Unknown")
    gallery = artifact.get("galleryName", "Museum Collection")
    category = artifact.get("category", "")
    institution = artifact.get("institution", "")
    period = artifact.get("period", "")
    origin = artifact.get("origin", "")
    description = artifact.get("description", "")
    
    ai_ctx = artifact.get("aiContext", {})
    significance = ai_ctx.get("historicalSignificance", "") if isinstance(ai_ctx, dict) else ""
    material = ai_ctx.get("material", "N/A") if isinstance(ai_ctx, dict) else "N/A"
    dimensions = ai_ctx.get("dimensions", "N/A") if isinstance(ai_ctx, dict) else "N/A"

    prompt = SYSTEM_PROMPT_TEMPLATE.format(
        name=name,
        gallery=gallery,
        category=category,
        institution=institution,
        period=period,
        origin=origin,
        description=description,
        significance=significance,
        material=material,
        dimensions=dimensions,
        question=question
    )

    # Priority 1: Groq API Key
    if keys["groq"]:
        try:
            return _call_groq_sdk(prompt, keys["groq"])
        except Exception as err:
            print(f"[LLM Error] Groq API call failed: {err}")
            raise RuntimeError(f"Grounded Groq LLM service error ({err})")

    # Priority 2: Gemini API Key
    elif keys["gemini"]:
        try:
            from google import genai
            client = genai.Client(api_key=keys["gemini"])
            res = client.models.generate_content(model="gemini-2.5-flash", contents=prompt)
            if res and res.text:
                return res.text.strip()
        except Exception as err:
            print(f"[LLM Error] Gemini API call failed: {err}")
            raise RuntimeError(f"Grounded Gemini LLM service error ({err})")

    # Fallback Warning if no API keys found
    print("[LLM Warning] No API key found (GROQ_API_KEY / GEMINI_API_KEY).")
    return f"Based on the curated record for {name} ({gallery}), {description}"
